### ISSUE TITLE
中文输入的字库看起来不全，如果要全部支持基本汉字20902个，还需要做多少工作？

### ISSUE THREAD

**Issue by lanistor** [100askTeam/lv_lib_100ask#1]
还有全部基本汉字的拼音映射文件大概有多大呢？

**Comment by YobeZhou** [comment]
1. 根据汉字 Unicode 编码标准，基本汉字有20902字，编码范围为4E00-9FA5，你可以阅读这里了解：http://lvgl.100ask.net/8.2/tools/fonts-zh-source.html#id8
2.  阅读这里了解如何使用lvgl的字体转换工具：http://lvgl.100ask.net/8.2/tools/fonts-zh-source.html#id10
3.  这里有转好的文件： https://github.com/100askTeam/lv_lib_100ask/blob/master/test/lv_100ask_chinese_ime_test/chinese-fonts.zip

**Comment by lanistor** [comment]
@YobeZhou 字体文件比较容易搞到，字体转换工具也好使用，但是怎么能把所有的汉字跟拼音映射好呢？
